### ISSUE TITLE
Thumb mouse button keybinds not working

### ISSUE THREAD

**Issue by verityyt** [incxption/valorant-configurator#1]
I originally had `Thumb Mouse Button` bind to `Equip Melee Weapon` but it was set to the `default value` i. e. `3`.

**Comment by verityyt** [comment]
And I originally had `Thumb Mouse Button 2` bind to `Ping: Caution` but it was set to the `default value` i. e. `nothing`.

**Comment by gomoritz** [comment]
Fixed in 8067b1037752611a9201f57781e76a7e07280d19.
